version: '3.1'

services:
  rabbitmq:
    image: "rabbitmq:3.8.6-management"
    container_name: rabbitmq-masterdev
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"

  spring-app:
    image: openjdk:21-jdk-slim
    container_name: spring-app
    ports:
      - 8080:8080
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
    volumes:
      - .:/app
    working_dir: /app
    command: [ "./mvnw", "spring-boot:run" ]
    depends_on:
      - rabbitmq